// Code generated by logcopter-gen; DO NOT EDIT.

package appconfig

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.remarquee.cmd.remarquee.internal.appconfig")
