service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 0
  }
}

service managesieve-login {
  inet_listener sieve {
    port = 4190
  }
}

service auth {
  unix_listener auth-userdb {
    mode = 0660
    user = vmail
    group = vmail
  }
}
