// Code generated by extract_color_map.py - DO NOT EDIT
// Source: rmscene.scene_items.PenColor and HARDCODED_COLORMAP

package remarkable

// PenColor represents the color of a pen/highlighter/shader
type PenColor int

const (
	BLACK PenColor = 0
	GRAY PenColor = 1
	WHITE PenColor = 2
	YELLOW PenColor = 3
	GREEN PenColor = 4
	PINK PenColor = 5
	BLUE PenColor = 6
	RED PenColor = 7
	GRAY_OVERLAP PenColor = 8
	HIGHLIGHT PenColor = 9
	GREEN_2 PenColor = 10
	CYAN PenColor = 11
	MAGENTA PenColor = 12
	YELLOW_2 PenColor = 13
	HIGHLIGHT_YELLOW PenColor = 14
	HIGHLIGHT_BLUE PenColor = 15
	HIGHLIGHT_PINK PenColor = 16
	HIGHLIGHT_ORANGE PenColor = 17
	HIGHLIGHT_GREEN PenColor = 18
	HIGHLIGHT_GRAY PenColor = 19
	SHADER_GRAY PenColor = 20
	SHADER_ORANGE PenColor = 21
	SHADER_MAGENTA PenColor = 22
	SHADER_BLUE PenColor = 23
	SHADER_RED PenColor = 24
	SHADER_GREEN PenColor = 25
	SHADER_YELLOW PenColor = 26
	SHADER_CYAN PenColor = 27
)

// RGBA represents a color with alpha channel
type RGBA struct {
	R, G, B, A uint8
}

// HardcodedColorMap maps RGBA values to PenColor enum values
// This is used to identify highlight colors in .rm files
var HardcodedColorMap = map[RGBA]PenColor{
	RGBA{255, 237, 117, 255}: HIGHLIGHT_YELLOW,
	RGBA{190, 234, 254, 255}: HIGHLIGHT_BLUE,
	RGBA{242, 158, 255, 255}: HIGHLIGHT_PINK,
	RGBA{255, 195, 140, 255}: HIGHLIGHT_ORANGE,
	RGBA{172, 255, 133, 255}: HIGHLIGHT_GREEN,
	RGBA{199, 199, 198, 255}: HIGHLIGHT_GRAY,
	RGBA{33, 30, 28, 64}: SHADER_GRAY,
	RGBA{254, 178, 0, 115}: SHADER_ORANGE,
	RGBA{192, 127, 210, 128}: SHADER_MAGENTA,
	RGBA{48, 74, 224, 77}: SHADER_BLUE,
	RGBA{194, 49, 50, 102}: SHADER_RED,
	RGBA{145, 218, 113, 128}: SHADER_GREEN,
	RGBA{250, 231, 25, 115}: SHADER_YELLOW,
	RGBA{116, 210, 232, 102}: SHADER_CYAN,
}

// PenColorToRGBA maps PenColor enum values to RGBA
var PenColorToRGBA = map[PenColor]RGBA{
	HIGHLIGHT_YELLOW: RGBA{255, 237, 117, 255},
	HIGHLIGHT_BLUE: RGBA{190, 234, 254, 255},
	HIGHLIGHT_PINK: RGBA{242, 158, 255, 255},
	HIGHLIGHT_ORANGE: RGBA{255, 195, 140, 255},
	HIGHLIGHT_GREEN: RGBA{172, 255, 133, 255},
	HIGHLIGHT_GRAY: RGBA{199, 199, 198, 255},
	SHADER_GRAY: RGBA{33, 30, 28, 64},
	SHADER_ORANGE: RGBA{254, 178, 0, 115},
	SHADER_MAGENTA: RGBA{192, 127, 210, 128},
	SHADER_BLUE: RGBA{48, 74, 224, 77},
	SHADER_RED: RGBA{194, 49, 50, 102},
	SHADER_GREEN: RGBA{145, 218, 113, 128},
	SHADER_YELLOW: RGBA{250, 231, 25, 115},
	SHADER_CYAN: RGBA{116, 210, 232, 102},
}

// PenColorToRGB converts PenColor to normalized RGB for PDF annotations
// Returns values in range [0.0, 1.0]
func PenColorToRGB(color PenColor) (r, g, b float64) {
	rgba, ok := PenColorToRGBA[color]
	if !ok {
		// Default to yellow highlight
		return 1.0, 0.93, 0.46
	}
	return float64(rgba.R)/255.0, float64(rgba.G)/255.0, float64(rgba.B)/255.0
}

// HighlightColors provides pre-computed normalized RGB values
var HighlightColors = map[PenColor][3]float64{
	HIGHLIGHT_YELLOW: {1.000000, 0.929412, 0.458824},
	HIGHLIGHT_BLUE: {0.745098, 0.917647, 0.996078},
	HIGHLIGHT_PINK: {0.949020, 0.619608, 1.000000},
	HIGHLIGHT_ORANGE: {1.000000, 0.764706, 0.549020},
	HIGHLIGHT_GREEN: {0.674510, 1.000000, 0.521569},
	HIGHLIGHT_GRAY: {0.780392, 0.780392, 0.776471},
	SHADER_GRAY: {0.129412, 0.117647, 0.109804},
	SHADER_ORANGE: {0.996078, 0.698039, 0.000000},
	SHADER_MAGENTA: {0.752941, 0.498039, 0.823529},
	SHADER_BLUE: {0.188235, 0.290196, 0.878431},
	SHADER_RED: {0.760784, 0.192157, 0.196078},
	SHADER_GREEN: {0.568627, 0.854902, 0.443137},
	SHADER_YELLOW: {0.980392, 0.905882, 0.098039},
	SHADER_CYAN: {0.454902, 0.823529, 0.909804},
}
