#!/usr/bin/env python3
"""
extract_color_map.py - Extract the PenColor → RGBA mapping for Go reimplementation.

This script generates Go code for the color mapping used by reMarkable highlights and shaders.

Run from the workspace root:
    python remarquee/ttmp/.../scripts/extract_color_map.py > remarquee/ttmp/.../scripts/color_map.go
"""

import sys
import pathlib

def main():
    # Add rmscene to path
    rmscene_path = pathlib.Path.home() / "workspaces/2025-12-14/build-remarquee-tool/rmscene/src"
    if not rmscene_path.exists():
        print("Error: rmscene not found at expected path", file=sys.stderr)
        print(f"Expected: {rmscene_path}", file=sys.stderr)
        sys.exit(1)
    
    sys.path.insert(0, str(rmscene_path))
    
    from rmscene.scene_items import PenColor, HARDCODED_COLORMAP
    
    print("// Code generated by extract_color_map.py - DO NOT EDIT")
    print("// Source: rmscene.scene_items.PenColor and HARDCODED_COLORMAP")
    print()
    print("package remarkable")
    print()
    
    print("// PenColor represents the color of a pen/highlighter/shader")
    print("type PenColor int")
    print()
    print("const (")
    for i, color in enumerate(PenColor):
        if i == 0:
            print(f"\t{color.name} PenColor = {color.value}")
        else:
            print(f"\t{color.name} PenColor = {color.value}")
    print(")")
    print()
    
    print("// RGBA represents a color with alpha channel")
    print("type RGBA struct {")
    print("\tR, G, B, A uint8")
    print("}")
    print()
    
    print("// HardcodedColorMap maps RGBA values to PenColor enum values")
    print("// This is used to identify highlight colors in .rm files")
    print("var HardcodedColorMap = map[RGBA]PenColor{")
    for rgba, pen_color in HARDCODED_COLORMAP.items():
        r, g, b, a = rgba
        print(f"\tRGBA{{{r}, {g}, {b}, {a}}}: {pen_color.name},")
    print("}")
    print()
    
    print("// PenColorToRGBA maps PenColor enum values to RGBA")
    print("var PenColorToRGBA = map[PenColor]RGBA{")
    for rgba, pen_color in HARDCODED_COLORMAP.items():
        r, g, b, a = rgba
        print(f"\t{pen_color.name}: RGBA{{{r}, {g}, {b}, {a}}},")
    print("}")
    print()
    
    print("// PenColorToRGB converts PenColor to normalized RGB for PDF annotations")
    print("// Returns values in range [0.0, 1.0]")
    print("func PenColorToRGB(color PenColor) (r, g, b float64) {")
    print("\trgba, ok := PenColorToRGBA[color]")
    print("\tif !ok {")
    print("\t\t// Default to yellow highlight")
    print("\t\treturn 1.0, 0.93, 0.46")
    print("\t}")
    print("\treturn float64(rgba.R)/255.0, float64(rgba.G)/255.0, float64(rgba.B)/255.0")
    print("}")
    print()
    
    print("// HighlightColors provides pre-computed normalized RGB values")
    print("var HighlightColors = map[PenColor][3]float64{")
    for rgba, pen_color in HARDCODED_COLORMAP.items():
        r, g, b, a = rgba
        print(f"\t{pen_color.name}: {{{r/255:.6f}, {g/255:.6f}, {b/255:.6f}}},")
    print("}")

if __name__ == "__main__":
    main()

