// Code generated by logcopter-gen; DO NOT EDIT.

package upload

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.remarquee.cmd.remarquee.cmds.upload")
