package mdpdf

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

func pandocAvailable(t *testing.T) {
	t.Helper()
	for _, p := range []string{"/usr/bin/pandoc", "/usr/local/bin/pandoc"} {
		if _, err := os.Stat(p); err == nil {
			return
		}
	}
	t.Skip("pandoc is not installed in a standard location")
}

func TestConvertMarkdownFileToPDFHandlesThematicBreakAndFencedYAML(t *testing.T) {
	pandocAvailable(t)

	td := t.TempDir()
	mdPath := filepath.Join(td, "thematic-break.md")
	mdContent := "# Thematic break regression\n\nParagraph before the separator.\n\n---\n\n## After the separator\n\n```yaml\n---\nkey: value\n---\n```\n"
	if err := os.WriteFile(mdPath, []byte(mdContent), 0o644); err != nil {
		t.Fatal(err)
	}

	outPDF := filepath.Join(td, "out.pdf")
	if err := ConvertMarkdownFileToPDF(context.Background(), mdPath, outPDF, DefaultPandocOptions()); err != nil {
		t.Fatalf("thematic break and fenced YAML conversion failed: %v", err)
	}

	pdfBytes, err := os.ReadFile(outPDF)
	if err != nil {
		t.Fatal(err)
	}
	if len(pdfBytes) < 4 || string(pdfBytes[:4]) != "%PDF" {
		t.Fatalf("expected PDF output, got prefix %q", string(pdfBytes[:min(len(pdfBytes), 16)]))
	}
}

func TestConvertMarkdownFileToPDFHandlesHashInInputFilename(t *testing.T) {
	pandocAvailable(t)

	td := t.TempDir()
	mdPath := filepath.Join(td, "PROJ - Example PR #6.md")
	outPDF := filepath.Join(td, "out.pdf")
	if err := os.WriteFile(mdPath, []byte("# Example\n\nBody.\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := ConvertMarkdownFileToPDF(context.Background(), mdPath, outPDF, DefaultPandocOptions()); err != nil {
		t.Fatalf("unexpected conversion error: %v", err)
	}
	if _, err := os.Stat(outPDF); err != nil {
		t.Fatalf("expected output PDF: %v", err)
	}
}

func TestConvertMarkdownFileToPDFWithRelativeOutputAndLatexHeader(t *testing.T) {
	pandocAvailable(t)

	td := t.TempDir()
	oldWD, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(td); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(oldWD) })

	if err := os.WriteFile("header.tex", []byte("% custom header\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile("doc.md", []byte("# Relative Paths\n\nBody.\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	opts := DefaultPandocOptions()
	opts.LatexHeaderFile = "header.tex"
	if err := ConvertMarkdownFileToPDF(context.Background(), "doc.md", "out.pdf", opts); err != nil {
		t.Fatalf("conversion with relative output/header failed: %v", err)
	}
	if _, err := os.Stat(filepath.Join(td, "out.pdf")); err != nil {
		t.Fatalf("expected relative output PDF in caller cwd: %v", err)
	}
}

func TestConvertMarkdownFileToPDFWithImage(t *testing.T) {
	pandocAvailable(t)

	td := t.TempDir()

	// Use a proper PNG from testdata (generated by scripts/01-gen-test-png.py).
	pngData, err := os.ReadFile("testdata/pixel.png")
	if err != nil {
		t.Skip("testdata/pixel.png not found (generate with scripts/01-gen-test-png.py)")
	}

	imgDir := filepath.Join(td, "assets")
	if err := os.MkdirAll(imgDir, 0o755); err != nil {
		t.Fatal(err)
	}
	imgPath := filepath.Join(imgDir, "pixel.png")
	if err := os.WriteFile(imgPath, pngData, 0o644); err != nil {
		t.Fatal(err)
	}

	mdContent := "# Image Test\n\n![pixel](./assets/pixel.png)\n"
	mdPath := filepath.Join(td, "doc.md")
	if err := os.WriteFile(mdPath, []byte(mdContent), 0o644); err != nil {
		t.Fatal(err)
	}

	outPDF := filepath.Join(td, "out.pdf")
	if err := ConvertMarkdownFileToPDF(context.Background(), mdPath, outPDF, DefaultPandocOptions()); err != nil {
		t.Fatalf("conversion with image failed: %v", err)
	}
	if _, err := os.Stat(outPDF); err != nil {
		t.Fatalf("expected output PDF: %v", err)
	}
}
