package mdpdf

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

func pandocAvailable(t *testing.T) {
	t.Helper()
	for _, p := range []string{"/usr/bin/pandoc", "/usr/local/bin/pandoc"} {
		if _, err := os.Stat(p); err == nil {
			return
		}
	}
	t.Skip("pandoc is not installed in a standard location")
}

func TestConvertMarkdownFileToPDFHandlesHashInInputFilename(t *testing.T) {
	pandocAvailable(t)

	td := t.TempDir()
	mdPath := filepath.Join(td, "PROJ - Example PR #6.md")
	outPDF := filepath.Join(td, "out.pdf")
	if err := os.WriteFile(mdPath, []byte("# Example\n\nBody.\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := ConvertMarkdownFileToPDF(context.Background(), mdPath, outPDF, DefaultPandocOptions()); err != nil {
		t.Fatalf("unexpected conversion error: %v", err)
	}
	if _, err := os.Stat(outPDF); err != nil {
		t.Fatalf("expected output PDF: %v", err)
	}
}

func TestConvertMarkdownFileToPDFWithImage(t *testing.T) {
	pandocAvailable(t)

	td := t.TempDir()

	// Use a proper PNG from testdata (generated by scripts/01-gen-test-png.py).
	pngData, err := os.ReadFile("testdata/pixel.png")
	if err != nil {
		t.Skip("testdata/pixel.png not found (generate with scripts/01-gen-test-png.py)")
	}

	imgDir := filepath.Join(td, "assets")
	if err := os.MkdirAll(imgDir, 0o755); err != nil {
		t.Fatal(err)
	}
	imgPath := filepath.Join(imgDir, "pixel.png")
	if err := os.WriteFile(imgPath, pngData, 0o644); err != nil {
		t.Fatal(err)
	}

	mdContent := "# Image Test\n\n![pixel](./assets/pixel.png)\n"
	mdPath := filepath.Join(td, "doc.md")
	if err := os.WriteFile(mdPath, []byte(mdContent), 0o644); err != nil {
		t.Fatal(err)
	}

	outPDF := filepath.Join(td, "out.pdf")
	if err := ConvertMarkdownFileToPDF(context.Background(), mdPath, outPDF, DefaultPandocOptions()); err != nil {
		t.Fatalf("conversion with image failed: %v", err)
	}
	if _, err := os.Stat(outPDF); err != nil {
		t.Fatalf("expected output PDF: %v", err)
	}
}
