// Code generated by logcopter-gen; DO NOT EDIT.

package pdfcmp

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.remarquee.pkg.pdfcmp")
