package rmdoc

// PenColor is the rmscene.scene_items.PenColor equivalent (subset used for highlights/shaders).
// This is ported from RMQ-0001 `scripts/color_map.go` (generated by extract_color_map.py).
type PenColor int

const (
	PenColorBlack PenColor = 0
	PenColorGray  PenColor = 1
	PenColorWhite PenColor = 2

	PenColorYellow PenColor = 3
	PenColorGreen  PenColor = 4
	PenColorPink   PenColor = 5
	PenColorBlue   PenColor = 6
	PenColorRed    PenColor = 7

	PenColorGrayOverlap PenColor = 8
	PenColorHighlight   PenColor = 9
	PenColorGreen2      PenColor = 10
	PenColorCyan        PenColor = 11
	PenColorMagenta     PenColor = 12
	PenColorYellow2     PenColor = 13

	PenColorHighlightYellow PenColor = 14
	PenColorHighlightBlue   PenColor = 15
	PenColorHighlightPink   PenColor = 16
	PenColorHighlightOrange PenColor = 17
	PenColorHighlightGreen  PenColor = 18
	PenColorHighlightGray   PenColor = 19

	PenColorShaderGray    PenColor = 20
	PenColorShaderOrange  PenColor = 21
	PenColorShaderMagenta PenColor = 22
	PenColorShaderBlue    PenColor = 23
	PenColorShaderRed     PenColor = 24
	PenColorShaderGreen   PenColor = 25
	PenColorShaderYellow  PenColor = 26
	PenColorShaderCyan    PenColor = 27
)

type RGBA struct {
	R, G, B, A uint8
}

// HardcodedColorMap maps RGBA values to PenColor enum values.
// This is used to identify highlight/shader colors in v6 .rm files (GlyphRanges, and sometimes lines).
var HardcodedColorMap = map[RGBA]PenColor{
	{R: 255, G: 237, B: 117, A: 255}: PenColorHighlightYellow,
	{R: 190, G: 234, B: 254, A: 255}: PenColorHighlightBlue,
	{R: 242, G: 158, B: 255, A: 255}: PenColorHighlightPink,
	{R: 255, G: 195, B: 140, A: 255}: PenColorHighlightOrange,
	{R: 172, G: 255, B: 133, A: 255}: PenColorHighlightGreen,
	{R: 199, G: 199, B: 198, A: 255}: PenColorHighlightGray,
	{R: 33, G: 30, B: 28, A: 64}:     PenColorShaderGray,
	{R: 254, G: 178, B: 0, A: 115}:   PenColorShaderOrange,
	{R: 192, G: 127, B: 210, A: 128}: PenColorShaderMagenta,
	{R: 48, G: 74, B: 224, A: 77}:    PenColorShaderBlue,
	{R: 194, G: 49, B: 50, A: 102}:   PenColorShaderRed,
	{R: 145, G: 218, B: 113, A: 128}: PenColorShaderGreen,
	{R: 250, G: 231, B: 25, A: 115}:  PenColorShaderYellow,
	{R: 116, G: 210, B: 232, A: 102}: PenColorShaderCyan,
}

// PenColorToRGB converts PenColor to normalized RGB for PDF annotations.
// Returns values in range [0.0, 1.0].
func PenColorToRGB(color PenColor) (r, g, b float64) {
	switch color {
	case PenColorBlack:
		return 0.0, 0.0, 0.0
	case PenColorGray:
		// rmc: (144,144,144)
		return 144.0 / 255.0, 144.0 / 255.0, 144.0 / 255.0
	case PenColorWhite:
		return 1.0, 1.0, 1.0
	case PenColorYellow:
		// rmc: (251,247,25)
		return 251.0 / 255.0, 247.0 / 255.0, 25.0 / 255.0
	case PenColorGreen:
		// rmc: (0,255,0)
		return 0.0, 1.0, 0.0
	case PenColorPink:
		// rmc: (255,192,203)
		return 1.0, 192.0 / 255.0, 203.0 / 255.0
	case PenColorBlue:
		// rmc: (78,105,201)
		return 78.0 / 255.0, 105.0 / 255.0, 201.0 / 255.0
	case PenColorRed:
		// rmc: (179,62,57)
		return 179.0 / 255.0, 62.0 / 255.0, 57.0 / 255.0
	case PenColorGrayOverlap:
		// rmc: (125,125,125)
		return 125.0 / 255.0, 125.0 / 255.0, 125.0 / 255.0
	case PenColorHighlight:
		// rmc: (247,232,81)
		return 247.0 / 255.0, 232.0 / 255.0, 81.0 / 255.0
	case PenColorGreen2:
		// rmc: (161,216,125)
		return 161.0 / 255.0, 216.0 / 255.0, 125.0 / 255.0
	case PenColorCyan:
		// rmc: (139,208,229)
		return 139.0 / 255.0, 208.0 / 255.0, 229.0 / 255.0
	case PenColorMagenta:
		// rmc: (183,130,205)
		return 183.0 / 255.0, 130.0 / 255.0, 205.0 / 255.0
	case PenColorYellow2:
		// rmc: (247,232,81)
		return 247.0 / 255.0, 232.0 / 255.0, 81.0 / 255.0
	case PenColorHighlightYellow:
		return 1.0, 0.929412, 0.458824
	case PenColorHighlightBlue:
		return 0.745098, 0.917647, 0.996078
	case PenColorHighlightPink:
		return 0.949020, 0.619608, 1.0
	case PenColorHighlightOrange:
		return 1.0, 0.764706, 0.549020
	case PenColorHighlightGreen:
		return 0.674510, 1.0, 0.521569
	case PenColorHighlightGray:
		return 0.780392, 0.780392, 0.776471
	case PenColorShaderGray:
		return 0.129412, 0.117647, 0.109804
	case PenColorShaderOrange:
		return 0.996078, 0.698039, 0.0
	case PenColorShaderMagenta:
		return 0.752941, 0.498039, 0.823529
	case PenColorShaderBlue:
		return 0.188235, 0.290196, 0.878431
	case PenColorShaderRed:
		return 0.760784, 0.192157, 0.196078
	case PenColorShaderGreen:
		return 0.568627, 0.854902, 0.443137
	case PenColorShaderYellow:
		return 0.980392, 0.905882, 0.098039
	case PenColorShaderCyan:
		return 0.454902, 0.823529, 0.909804
	default:
		// Default to yellow highlight.
		return 1.0, 0.93, 0.46
	}
}

// PenColorToRGBForStroke converts PenColor to normalized RGB for stroke rendering.
//
// This differs from PenColorToRGB in one important way: if the color is unknown,
// strokes should default to black (not highlight yellow), because "unknown pen color"
// should not paint the document yellow.
func PenColorToRGBForStroke(color PenColor) (r, g, b float64) {
	switch color {
	case PenColorBlack,
		PenColorGray,
		PenColorWhite,
		PenColorYellow,
		PenColorGreen,
		PenColorPink,
		PenColorBlue,
		PenColorRed,
		PenColorGrayOverlap,
		PenColorHighlight,
		PenColorGreen2,
		PenColorCyan,
		PenColorMagenta,
		PenColorYellow2,
		PenColorHighlightYellow,
		PenColorHighlightBlue,
		PenColorHighlightPink,
		PenColorHighlightOrange,
		PenColorHighlightGreen,
		PenColorHighlightGray,
		PenColorShaderGray,
		PenColorShaderOrange,
		PenColorShaderMagenta,
		PenColorShaderBlue,
		PenColorShaderRed,
		PenColorShaderGreen,
		PenColorShaderYellow,
		PenColorShaderCyan:
		return PenColorToRGB(color)
	default:
		return 0.0, 0.0, 0.0
	}
}
